# Generated by Django 6.0.4 on 2026-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('africas_talking', "Africa's Talking")], default='africas_talking', max_length=40)),
                ('event_type', models.CharField(default='unknown', max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
